throw Error('test failed')
// process.exit(2)